<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://group.vodafone.com/schema/vbm/payment/customer-money-transfer/v2"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:tns="http://www.example.org"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://group.vodafone.com/schema/extension/vbo/payment/customer-money-transfer/v2"
                xmlns:vbo="http://group.vodafone.com/schema/vbo/payment/customer-money-transfer/v2"
                xmlns:cmn="http://group.vodafone.com/schema/common/v1"
                xmlns:ns2="urn:un:unece:uncefact:documentation:standard:CoreComponentType:2">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/CustomerMoneyTransferVBM.xsd"/>
                <oracle-xsl-mapper:rootElement name="CreateCustomerMoneyTransferVBMResponse"
                                               namespace="http://group.vodafone.com/schema/vbm/payment/customer-money-transfer/v2"/>
                <oracle-xsl-mapper:param name="createCustomerMoneyTransferVBMResponse"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/TibocResponse.xsd"/>
                <oracle-xsl-mapper:rootElement name="TibcoResponse" namespace="http://www.example.org"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SAT MAY 12 00:32:53 EET 2018].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:TibcoResponse>
            <tns:TransactionID>
                <xsl:value-of select="/ns0:CreateCustomerMoneyTransferVBMResponse/ns0:CustomerMoneyTransferVBO/cmn:IDs/cmn:ID[@schemeID='TransactionID']"/>
            </tns:TransactionID>
            <tns:TransferID>
                <xsl:value-of select="/ns0:CreateCustomerMoneyTransferVBMResponse/ns0:CustomerMoneyTransferVBO/cmn:IDs/cmn:ID[@schemeID='TransferID']"/>
            </tns:TransferID>
            <tns:Status>
                <xsl:value-of select="/ns0:CreateCustomerMoneyTransferVBMResponse/ns0:CustomerMoneyTransferVBO/cmn:Status"/>
            </tns:Status>
           <tns:ErrorCode></tns:ErrorCode>
            <tns:Description></tns:Description>
        </tns:TibcoResponse>
    </xsl:template>
</xsl:stylesheet>
