<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://group.vodafone.com/schema/vbm/payment/customer-money-transfer/v2"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://www.example.org"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://group.vodafone.com/schema/extension/vbo/payment/customer-money-transfer/v2"
                xmlns:vbo="http://group.vodafone.com/schema/vbo/payment/customer-money-transfer/v2"
                xmlns:cmn="http://group.vodafone.com/schema/common/v1"
                xmlns:ns2="urn:un:unece:uncefact:documentation:standard:CoreComponentType:2">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/TibcoRequest.xsd"/>
                <oracle-xsl-mapper:rootElement name="TibcoRequest" namespace="http://www.example.org"/>
                <oracle-xsl-mapper:param name="customerTransferRequest"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/CustomerMoneyTransferVBM.xsd"/>
                <oracle-xsl-mapper:rootElement name="CreateCustomerMoneyTransferVBMRequest"
                                               namespace="http://group.vodafone.com/schema/vbm/payment/customer-money-transfer/v2"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SAT MAY 12 00:22:18 EET 2018].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:CreateCustomerMoneyTransferVBMRequest>
            <tns:CustomerMoneyTransferVBO>
                <cmn:Type>Loan</cmn:Type>
                <vbo:Roles>
                    <vbo:Payer>
                        <cmn:IDs>
                            <cmn:ID schemeID="FundingMSISDN">
                                <xsl:value-of select="/ns0:TibcoRequest/ns0:FoundingMSISDN"/>
                            </cmn:ID>
                        </cmn:IDs>
                    </vbo:Payer>
                    <vbo:Receiver>
                        <cmn:IDs>
                            <cmn:ID schemeID="MSISDN">
                                <xsl:value-of select="/ns0:TibcoRequest/ns0:MSISDN"/>
                            </cmn:ID>
                            <cmn:ID schemeID="PIN">
                                <xsl:value-of select="/ns0:TibcoRequest/ns0:PIN"/>
                            </cmn:ID>
                        </cmn:IDs>
                    </vbo:Receiver>
                </vbo:Roles>
                <vbo:Parts>
                    <vbo:PaymentMethod>
                        <cmn:Type>VFCash</cmn:Type>
                        <cmn:Categories>
                            <cmn:Category>Solfa</cmn:Category>
                        </cmn:Categories>
                        <vbo:Amount>
                            <xsl:value-of select="/ns0:TibcoRequest/ns0:Amount"/>
                        </vbo:Amount>
                        <vbo:Channel>
                            <cmn:IDs>
                                <cmn:ID schemeID="PASS">HRToolPass</cmn:ID>
                            </cmn:IDs>
                            <cmn:Name>HRTool</cmn:Name>
                        </vbo:Channel>
                    </vbo:PaymentMethod>
                    <vbo:Specification>
                        <cmn:CharacteristicsValue characteristicName="LANGUAGE">
                            <cmn:Value>1</cmn:Value>
                        </cmn:CharacteristicsValue>
                    </vbo:Specification>
                </vbo:Parts>
            </tns:CustomerMoneyTransferVBO>
        </tns:CreateCustomerMoneyTransferVBMRequest>
    </xsl:template>
</xsl:stylesheet>
