package com.truemega.solfa.model.common;

import java.util.ArrayList;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 14 15:02:12 EET 2018
// ---------------------------------------------------------------------
public interface SolfaAppModule extends ApplicationModule {

    void closeOpenedRequest();


    void insertTrackData();

    void removeEmployeeData();

    boolean isDirty();
}

