package com.truemega.solfa.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 16 00:59:26 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SolfaRequestsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SolfaRequestsViewImpl() {
    }

    /**
     * Returns the bind variable value for staffIdBind.
     * @return bind variable value for staffIdBind
     */
    public String getstaffIdBind() {
        return (String) getNamedWhereClauseParam("staffIdBind");
    }

    /**
     * Sets <code>value</code> for bind variable staffIdBind.
     * @param value value to bind as staffIdBind
     */
    public void setstaffIdBind(String value) {
        setNamedWhereClauseParam("staffIdBind", value);
    }
}

