package com.truemega.solfa.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 02 14:25:07 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SolfaEmployeesViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SolfaEmployeesViewImpl() {
    }
}

