package com.truemega.solfa.model.view;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 16 00:59:25 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SolfaRequestsViewRowImpl extends ViewRowImpl {

    public static final int ENTITY_SOLFAREQUESTS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RequestNumber,
        RequestDate,
        StaffId,
        Msisdn,
        Pin,
        AmountAllowed,
        AmountRequested,
        RequestStatus,
        EmployeeBand;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int REQUESTNUMBER = AttributesEnum.RequestNumber.index();
    public static final int REQUESTDATE = AttributesEnum.RequestDate.index();
    public static final int STAFFID = AttributesEnum.StaffId.index();
    public static final int MSISDN = AttributesEnum.Msisdn.index();
    public static final int PIN = AttributesEnum.Pin.index();
    public static final int AMOUNTALLOWED = AttributesEnum.AmountAllowed.index();
    public static final int AMOUNTREQUESTED = AttributesEnum.AmountRequested.index();
    public static final int REQUESTSTATUS = AttributesEnum.RequestStatus.index();
    public static final int EMPLOYEEBAND = AttributesEnum.EmployeeBand.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SolfaRequestsViewRowImpl() {
    }

    /**
     * Gets SolfaRequests entity object.
     * @return the SolfaRequests
     */
    public EntityImpl getSolfaRequests() {
        return (EntityImpl) getEntity(ENTITY_SOLFAREQUESTS);
    }

    /**
     * Gets the attribute value for REQUEST_NUMBER using the alias name RequestNumber.
     * @return the REQUEST_NUMBER
     */
    public DBSequence getRequestNumber() {
        return (DBSequence) getAttributeInternal(REQUESTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_NUMBER using the alias name RequestNumber.
     * @param value value to set the REQUEST_NUMBER
     */
    public void setRequestNumber(DBSequence value) {
        setAttributeInternal(REQUESTNUMBER, value);
    }

    /**
     * Gets the attribute value for REQUEST_DATE using the alias name RequestDate.
     * @return the REQUEST_DATE
     */
    public Date getRequestDate() {
        return (Date) getAttributeInternal(REQUESTDATE);
    }

    /**
     * Gets the attribute value for STAFF_ID using the alias name StaffId.
     * @return the STAFF_ID
     */
    public String getStaffId() {
        return (String) getAttributeInternal(STAFFID);
    }

    /**
     * Sets <code>value</code> as attribute value for STAFF_ID using the alias name StaffId.
     * @param value value to set the STAFF_ID
     */
    public void setStaffId(String value) {
        setAttributeInternal(STAFFID, value);
    }

    /**
     * Gets the attribute value for MSISDN using the alias name Msisdn.
     * @return the MSISDN
     */
    public String getMsisdn() {
        return (String) getAttributeInternal(MSISDN);
    }

    /**
     * Sets <code>value</code> as attribute value for MSISDN using the alias name Msisdn.
     * @param value value to set the MSISDN
     */
    public void setMsisdn(String value) {
        setAttributeInternal(MSISDN, value);
    }

    /**
     * Gets the attribute value for PIN using the alias name Pin.
     * @return the PIN
     */
    public String getPin() {
        return (String) getAttributeInternal(PIN);
    }

    /**
     * Sets <code>value</code> as attribute value for PIN using the alias name Pin.
     * @param value value to set the PIN
     */
    public void setPin(String value) {
        setAttributeInternal(PIN, value);
    }

    /**
     * Gets the attribute value for AMOUNT_ALLOWED using the alias name AmountAllowed.
     * @return the AMOUNT_ALLOWED
     */
    public String getAmountAllowed() {
        return (String) getAttributeInternal(AMOUNTALLOWED);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT_ALLOWED using the alias name AmountAllowed.
     * @param value value to set the AMOUNT_ALLOWED
     */
    public void setAmountAllowed(String value) {
        setAttributeInternal(AMOUNTALLOWED, value);
    }

    /**
     * Gets the attribute value for AMOUNT_REQUESTED using the alias name AmountRequested.
     * @return the AMOUNT_REQUESTED
     */
    public String getAmountRequested() {
        return (String) getAttributeInternal(AMOUNTREQUESTED);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT_REQUESTED using the alias name AmountRequested.
     * @param value value to set the AMOUNT_REQUESTED
     */
    public void setAmountRequested(String value) {
        setAttributeInternal(AMOUNTREQUESTED, value);
    }

    /**
     * Gets the attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @return the REQUEST_STATUS
     */
    public String getRequestStatus() {
        return (String) getAttributeInternal(REQUESTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @param value value to set the REQUEST_STATUS
     */
    public void setRequestStatus(String value) {
        setAttributeInternal(REQUESTSTATUS, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_BAND using the alias name EmployeeBand.
     * @return the EMPLOYEE_BAND
     */
    public String getEmployeeBand() {
        return (String) getAttributeInternal(EMPLOYEEBAND);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_BAND using the alias name EmployeeBand.
     * @param value value to set the EMPLOYEE_BAND
     */
    public void setEmployeeBand(String value) {
        setAttributeInternal(EMPLOYEEBAND, value);
    }
}

