package com.truemega.solfa.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 16 18:02:00 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SolfaEmployeesTrackViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SolfaEmployeesTrackViewImpl() {
    }
}

