--------------------------------------------------------
--  File created - Sunday-July-15-2018   
--------------------------------------------------------
Create user hrat_slf identified by 123 account unlock;
grant dba to hrat_slf ;
connect hrat_slf/123;
--------------------------------------------------------
--  DDL for Sequence SOLFA_EMPLOYEES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SOLFA_EMPLOYEES_SEQ"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 20841 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SOLFA_REQUESTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SOLFA_REQUESTS_SEQ"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SOLFA_TRACK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SOLFA_TRACK_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table SOLFA_EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "SOLFA_EMPLOYEES" ("SOLFA_EMP_ID" NUMBER, "STAFF_ID" VARCHAR2(20), "HAS_SOLFA" VARCHAR2(1), "SOLFA_AMOUNT" VARCHAR2(20), "CREATED_DATE" DATE) ;
--------------------------------------------------------
--  DDL for Table SOLFA_EMPLOYEES_TRACK
--------------------------------------------------------

  CREATE TABLE "SOLFA_EMPLOYEES_TRACK" ("TRACKID" NUMBER(30,0), "HAS_SOLFA" VARCHAR2(1), "SOLFA_AMOUNT" VARCHAR2(20), "CREATED_DATE" DATE, "STAFF_ID" VARCHAR2(20)) ;
--------------------------------------------------------
--  DDL for Table SOLFA_REQUESTS
--------------------------------------------------------

  CREATE TABLE "SOLFA_REQUESTS" ("REQUEST_NUMBER" NUMBER, "REQUEST_DATE" DATE, "STAFF_ID" VARCHAR2(20), "MSISDN" VARCHAR2(20), "PIN" VARCHAR2(20), "AMOUNT_ALLOWED" VARCHAR2(20), "AMOUNT_REQUESTED" VARCHAR2(20), "REQUEST_STATUS" VARCHAR2(20), "EMPLOYEE_BAND" VARCHAR2(20)) ;
REM INSERTING into SOLFA_EMPLOYEES
SET DEFINE OFF;
REM INSERTING into SOLFA_EMPLOYEES_TRACK
SET DEFINE OFF;
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (1,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'1');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (2,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'2');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (3,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'3');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (4,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'4');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (5,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'5');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (6,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'6');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (7,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'7');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (8,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'8');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (9,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'9');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (10,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'10');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (11,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'11');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (12,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'12');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (13,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'13');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (14,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'14');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (15,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'15');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (16,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'16');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (17,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'17');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (18,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'18');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (19,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'19');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (20,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'20');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (21,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'21');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (22,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'22');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (23,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'23');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (24,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'24');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (25,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'25');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (26,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'26');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (27,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'27');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (28,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'28');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (29,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'29');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (30,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'30');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (31,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'31');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (32,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'32');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (33,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'33');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (34,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'34');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (35,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'35');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (36,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'36');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (37,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'37');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (38,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'38');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (39,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'39');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (40,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'40');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (41,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'41');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (42,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'42');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (43,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'43');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (44,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'44');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (45,'Y','2323',to_timestamp('09-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'45');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (46,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'1');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (47,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'2');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (48,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'3');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (49,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'4');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (50,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'5');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (51,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'6');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (52,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'7');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (53,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'8');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (54,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'9');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (55,'N','5555',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'10');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (56,'N','3234',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'11');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (57,'N','6665',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'12');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (58,'N','9877',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'13');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (59,'N','567',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'14');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (60,'N','545',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'15');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (61,'N','9876',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'16');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (62,'N','7654',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'17');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (63,'Y','2345',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'18');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (64,'Y','7654',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'19');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (65,'Y','5678',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'20');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (66,'Y','8765',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'21');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (67,'Y','2344',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'22');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (68,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'1');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (69,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'2');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (70,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'3');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (71,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'4');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (72,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'5');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (73,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'6');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (74,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'7');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (75,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'8');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (76,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'9');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (77,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'10');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (78,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'11');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (79,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'12');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (80,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'13');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (81,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'14');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (82,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'15');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (83,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'16');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (84,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'17');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (85,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'18');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (86,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'19');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (87,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'20');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (88,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'21');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (89,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'22');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (90,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'23');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (91,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'24');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (92,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'25');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (93,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'26');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (94,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'27');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (95,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'28');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (96,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'29');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (97,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'30');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (98,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'31');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (99,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'32');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (100,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'33');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (101,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'34');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (102,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'35');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (103,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'36');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (104,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'37');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (105,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'38');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (106,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'39');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (107,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'40');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (108,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'41');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (109,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'42');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (110,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'43');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (111,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'44');
Insert into SOLFA_EMPLOYEES_TRACK (TRACKID,HAS_SOLFA,SOLFA_AMOUNT,CREATED_DATE,STAFF_ID) values (112,'Y','2323',to_timestamp('15-JUL-18','DD-MON-RR HH.MI.SSXFF AM'),'45');
REM INSERTING into SOLFA_REQUESTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger SOLFA_EMPLOYEES_TRACK_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOLFA_EMPLOYEES_TRACK_TRG" 
   before insert on "SOLFA_EMPLOYEES_TRACK" 
   for each row 
begin  
   if inserting then 
      if :NEW."TRACKID" is null then 
         select SOLFA_TRACK_SEQ.nextval into :NEW."TRACKID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SOLFA_EMPLOYEES_TRACK_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SOLFA_EMPLOYEES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOLFA_EMPLOYEES_TRG" 
   before insert on "SOLFA_EMPLOYEES" 
   for each row 
begin  
   if inserting then 
      if :NEW."SOLFA_EMP_ID" is null then 
         select SOLFA_EMPLOYEES_SEQ.nextval into :NEW."SOLFA_EMP_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SOLFA_EMPLOYEES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SOLFA_REQUESTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SOLFA_REQUESTS_TRG" 
   before insert on "SOLFA_REQUESTS" 
   for each row 
begin  
   if inserting then 
      if :NEW."REQUEST_NUMBER" is null then 
         select SOLFA_REQUESTS_SEQ.nextval into :NEW."REQUEST_NUMBER" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SOLFA_REQUESTS_TRG" ENABLE;
