<wsdl:definitions
     name="getCountRequests-dbReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SolfaRequestApplication/BpmTibcoIntegration/getCountRequests_dbReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SolfaRequestApplication/BpmTibcoIntegration/getCountRequests_dbReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/getCountRequests-dbReference"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="getCountRequests_dbReference_plt" >
    <plt:role name="getCountRequests-dbReference_role" >
      <plt:portType name="tns:getCountRequests_dbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="getCountRequests_dbReference_plt" >
    <plt:role name="getCountRequests-dbReference_role" >
      <plt:portType name="tns:getCountRequests_dbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="getCountRequests_dbReference_plt" >
    <plt:role name="getCountRequests-dbReference_role" >
      <plt:portType name="tns:getCountRequests_dbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="getCountRequests_dbReference_plt" >
    <plt:role name="getCountRequests-dbReference_role" >
      <plt:portType name="tns:getCountRequests_dbReference_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getCountRequests-dbReference" schemaLocation="../Schemas/getCountRequests_dbReference.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getCountRequests-dbReference" schemaLocation="../Schemas/getCountRequests_dbReference.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getCountRequests-dbReference" schemaLocation="../Schemas/getCountRequests_dbReference.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getCountRequests-dbReference" schemaLocation="../Schemas/getCountRequests_dbReference.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="getCountRequests-dbReferenceInput_msg">
        <wsdl:part name="getCountRequests-dbReferenceInput_msg" element="db:getCountRequests-dbReferenceInput"/>
    </wsdl:message>
    <wsdl:message name="getCountRequests-dbReferenceOutput_msg">
        <wsdl:part name="getCountRequests-dbReferenceOutput" element="db:getCountRequests-dbReferenceOutput"/>
    </wsdl:message>
    <wsdl:portType name="getCountRequests_dbReference_ptt">
        <wsdl:operation name="getCountRequests-dbReference">
            <wsdl:input message="tns:getCountRequests-dbReferenceInput_msg"/>
            <wsdl:output message="tns:getCountRequests-dbReferenceOutput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
